[tool.poetry]
name = "horoscope"
version = "0.1.0"
description = ""
authors = ["lomalo890 <george2066@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
